version: '3.8'

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - DATABASE_HOST=127.0.0.1
    ports:
      - "5000:5000"

      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - DATABASE_HOST=127.0.0.1
    ports:
      - "5000:5432"


    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)


